GET http://localhost:8000/api/test-api
Content-Type: application/json
Authorization: token
###
POST http://localhost:8000/api/register
Accept: : application/json
Content-Type: application/json

{
    "email" : "mail@mail.com",
    "name" : "Diki",
    "password" : "password2",
    "password_confirmation" : "password2"
}

###
POST http://localhost:8000/api/login
Content-Type: : application/json
Accept: application/json

{
    "email" : "mail@mail.com",
    "password" : "password2"
}

###

GET http://localhost:8000/api/test-token
Accept: application/json
Authorization: Bearer 1|RQj6LjwmF2hAn5MkdSaXPIddIXuvo8afK5OvD2tMb2b3bfe2
